version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.22.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: |
          yarn global add greenkeeper-lockfile@1
          yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: |
          $HOME/.config/yarn/global/node_modules/.bin/greenkeeper-lockfile-update
          yarn test
          $HOME/.config/yarn/global/node_modules/.bin/greenkeeper-lockfile-upload

workflows:
  version: 2
  commit:
    jobs:
      - test
